/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nutrehogar.sistemacontable.ui.view.defaultImple;

import com.nutrehogar.sistemacontable.ui.view.DashboardView;
import lombok.Getter;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 * @author Calci
 */
@Getter
public class DefaultDashboardView extends DashboardView {

    /**
     * Creates new form DefaultDashboardView
     */
    public DefaultDashboardView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        btnShowFormView = new javax.swing.JButton();
        btnShowJournalView = new javax.swing.JButton();
        btnShowTrialBalanceView = new javax.swing.JButton();
        btnShowBackupView = new javax.swing.JButton();
        btnShowGeneralLedgerView = new javax.swing.JButton();
        btnShowAccountSubtypeView = new javax.swing.JButton();
        btnShowAccountView = new javax.swing.JButton();

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnShowFormView.setText("Form");

        btnShowJournalView.setText("Journal");

        btnShowTrialBalanceView.setText("TrailBalance");

        btnShowBackupView.setText("backup");

        btnShowGeneralLedgerView.setText("General");

        btnShowAccountSubtypeView.setText("AccountSubtype");

        btnShowAccountView.setText("Account");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowBackupView)
                    .addComponent(btnShowAccountSubtypeView)
                    .addComponent(btnShowAccountView)
                    .addComponent(btnShowGeneralLedgerView)
                    .addComponent(btnShowTrialBalanceView)
                    .addComponent(btnShowJournalView)
                    .addComponent(btnShowFormView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnShowFormView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowJournalView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowTrialBalanceView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowGeneralLedgerView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShowAccountView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowAccountSubtypeView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowBackupView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowAccountSubtypeView;
    private javax.swing.JButton btnShowAccountView;
    private javax.swing.JButton btnShowBackupView;
    private javax.swing.JButton btnShowFormView;
    private javax.swing.JButton btnShowGeneralLedgerView;
    private javax.swing.JButton btnShowJournalView;
    private javax.swing.JButton btnShowTrialBalanceView;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
