/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nutrehogar.sistemacontable.ui.view.imple;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import lombok.Getter;

/**
 * @author Calci
 */
@Getter
public class DefaultDashboardView extends PanelDashboardView {
    private final int ICON_SIZE = 50;

    /**
     * Creates new form DefaultDashboardView
     */
    public DefaultDashboardView() {
        initComponents();
        btnHome.setIcon(new FlatSVGIcon("svgs/home.svg", 40, 40));
        btnShowFormView.setIcon(getIcon("svgs/form.svg"));
        btnShowJournalView.setIcon(getIcon("svgs/journal.svg"));
        btnShowTrialBalanceView.setIcon(getIcon("svgs/trial_balance.svg"));
        btnShowGeneralLedgerView.setIcon(getIcon("svgs/general_ledger.svg"));
        btnShowAccountView.setIcon(getIcon("svgs/account.svg"));
        btnShowAccountSubtypeView.setIcon(getIcon("svgs/account_subtype.svg"));
        btnShowBackupView.setIcon(getIcon("svgs/backup.svg"));
    }

    private FlatSVGIcon getIcon(String iconName) {
        return new FlatSVGIcon(iconName, ICON_SIZE, ICON_SIZE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        pnlGroupBtn = new javax.swing.JPanel();
        btnShowFormView = new com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton();
        btnShowAccountView = new com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton();
        btnShowTrialBalanceView = new com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton();
        btnShowAccountSubtypeView = new com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton();
        btnShowGeneralLedgerView = new com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton();
        btnShowJournalView = new com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton();
        pnlNav = new javax.swing.JPanel();
        btnShowBackupView = new com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton();
        btnHome = new com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlContent.setOpaque(false);

        pnlHome.setOpaque(false);

        pnlGroupBtn.setOpaque(false);

        btnShowFormView.setText("Formulario");
        btnShowFormView.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        btnShowAccountView.setText("Cuentas");
        btnShowAccountView.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        btnShowTrialBalanceView.setText("Balance de Comprobacion");
        btnShowTrialBalanceView.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        btnShowAccountSubtypeView.setText("SubtipoCuentas");
        btnShowAccountSubtypeView.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        btnShowGeneralLedgerView.setText("Mayor General");
        btnShowGeneralLedgerView.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        btnShowJournalView.setText("Libro Diario");
        btnShowJournalView.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N

        javax.swing.GroupLayout pnlGroupBtnLayout = new javax.swing.GroupLayout(pnlGroupBtn);
        pnlGroupBtn.setLayout(pnlGroupBtnLayout);
        pnlGroupBtnLayout.setHorizontalGroup(
            pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowAccountView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowTrialBalanceView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowFormView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnShowAccountSubtypeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowGeneralLedgerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowJournalView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlGroupBtnLayout.setVerticalGroup(
            pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                .addGroup(pnlGroupBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                        .addComponent(btnShowFormView, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowTrialBalanceView, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowAccountView, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addGroup(pnlGroupBtnLayout.createSequentialGroup()
                        .addComponent(btnShowJournalView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowGeneralLedgerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowAccountSubtypeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(pnlGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(pnlGroupBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlNav.setOpaque(false);

        btnShowBackupView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnShowBackupView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShowBackupView.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        btnHome.setText("Inicio");
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlNavLayout = new javax.swing.GroupLayout(pnlNav);
        pnlNav.setLayout(pnlNavLayout);
        pnlNavLayout.setHorizontalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowBackupView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlNavLayout.setVerticalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowBackupView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton btnHome;
    private com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton btnShowAccountSubtypeView;
    private com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton btnShowAccountView;
    private com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton btnShowBackupView;
    private com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton btnShowFormView;
    private com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton btnShowGeneralLedgerView;
    private com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton btnShowJournalView;
    private com.nutrehogar.sistemacontable.ui.JComponents.impl.DefaultPanelButton btnShowTrialBalanceView;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlGroupBtn;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlNav;
    // End of variables declaration//GEN-END:variables

}
