/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nutrehogar.sistemacontable.ui.view;

import com.formdev.flatlaf.FlatLightLaf;
import com.nutrehogar.sistemacontable.application.config.HibernateUtil;
import com.nutrehogar.sistemacontable.application.repository.SimpleRepository;
import com.nutrehogar.sistemacontable.application.repository.crud.CuentaRepository;
import com.nutrehogar.sistemacontable.application.repository.crud.SubTipoCuentaRepository;
import com.nutrehogar.sistemacontable.application.repository.crud.TipoCuentaRepository;
import com.nutrehogar.sistemacontable.domain.BalanceCheckRepositoryImpl;
import com.nutrehogar.sistemacontable.domain.core.CRUDRepositoryFactory;
import com.nutrehogar.sistemacontable.domain.model.Cuenta;
import com.nutrehogar.sistemacontable.domain.model.SubTipoCuenta;
import com.nutrehogar.sistemacontable.domain.model.TipoCuenta;
import com.nutrehogar.sistemacontable.ui.controller.AccountController;
import com.nutrehogar.sistemacontable.ui.controller.BalanceCheckController;
import com.nutrehogar.sistemacontable.ui.controller.Controller;
import org.hibernate.Session;

import java.awt.*;
import javax.swing.*;

/**
 * @author Calci
 */
public class MainContent extends javax.swing.JFrame {
    Session session;
    Controller controller;
    SubTipoCuentaRepository subTipoRepository;
    TipoCuentaRepository tipoRepository;
    CuentaRepository repository;
    AccountView view;
    JFrame main;

    /**
     * Creates new form MainContent
     */
    public MainContent() {
        initComponents();
        session = HibernateUtil.getSession();
//        view = new BalanceCheckView();
//        repository = new BalanceCheckRepositoryImpl(session);
//        controller = new BalanceCheckController(repository, view);
//        var balan = controller.getView();
        view = new AccountView();
        repository = CRUDRepositoryFactory.createRepository(CuentaRepository.class, Cuenta.class, session);
        subTipoRepository = CRUDRepositoryFactory.createRepository(SubTipoCuentaRepository.class, SubTipoCuenta.class, session);
        tipoRepository = CRUDRepositoryFactory.createRepository(TipoCuentaRepository.class, TipoCuenta.class, session);
        controller = new AccountController(repository, view, subTipoRepository, tipoRepository);
        setContent(view);
    }

    public void setContent(JPanel p) {
        content.removeAll();
        content.setLayout(new BorderLayout());  // Añade esta línea para restablecer el diseño del Content
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 645, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.setProperty("flatlaf.useWindowDecorations", "true");
        FlatLightLaf.setup();
        EventQueue.invokeLater(() -> new MainContent().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel content;
    // End of variables declaration//GEN-END:variables
}
