create table account
(
    id                 integer      not null
        primary key,
    name               varchar(255) not null,
    id_account_subtype integer      not null
);

INSERT INTO account (id, name, id_account_subtype) VALUES (11020, 'Caja Menuda', 11);
INSERT INTO account (id, name, id_account_subtype) VALUES (11030, 'Caja Menuda del MIDES', 11);
INSERT INTO account (id, name, id_account_subtype) VALUES (11051, 'Banco Nacional de Panamá-MIDES', 11);
INSERT INTO account (id, name, id_account_subtype) VALUES (11090, 'Banco Global Bank Corp.', 11);
INSERT INTO account (id, name, id_account_subtype) VALUES (11100, 'Caja General', 11);
INSERT INTO account (id, name, id_account_subtype) VALUES (13000, 'Alimentos', 13);
INSERT INTO account (id, name, id_account_subtype) VALUES (13001, 'Útiles de Limpieza y Aseo', 13);
INSERT INTO account (id, name, id_account_subtype) VALUES (13002, 'Enseres', 13);
INSERT INTO account (id, name, id_account_subtype) VALUES (13003, 'Medicamentos', 13);
INSERT INTO account (id, name, id_account_subtype) VALUES (13004, 'Ropa de los Niños', 13);
INSERT INTO account (id, name, id_account_subtype) VALUES (13005, 'Juguetes', 13);
INSERT INTO account (id, name, id_account_subtype) VALUES (13006, 'Otros', 13);
INSERT INTO account (id, name, id_account_subtype) VALUES (15000, 'Cta. Por Cobrar - Empleados', 15);
INSERT INTO account (id, name, id_account_subtype) VALUES (15001, 'Cta. Por Cobrar - Actividad', 15);
INSERT INTO account (id, name, id_account_subtype) VALUES (15002, 'Cta. Por Cobrar - Cuotas', 15);
INSERT INTO account (id, name, id_account_subtype) VALUES (15003, 'Cta. Por Cobrar - Nutre Hogar Nacional', 15);
INSERT INTO account (id, name, id_account_subtype) VALUES (15004, 'Cta. Por Cobrar - Nutre Hogar Rifa', 15);
INSERT INTO account (id, name, id_account_subtype) VALUES (15005, 'Cta. Por Cobrar - Mides', 15);
INSERT INTO account (id, name, id_account_subtype) VALUES (15006, 'Cta. Por Cobrar - Otros', 15);
INSERT INTO account (id, name, id_account_subtype) VALUES (16000, 'Edificio', 16);
INSERT INTO account (id, name, id_account_subtype) VALUES (16001, 'Equipo de Oficina', 16);
INSERT INTO account (id, name, id_account_subtype) VALUES (16002, 'Equipo de Médico y Enfermería', 16);
INSERT INTO account (id, name, id_account_subtype) VALUES (16003, 'Transporte', 16);
INSERT INTO account (id, name, id_account_subtype) VALUES (16004, 'Equipo de Aire Acondicionado', 16);
INSERT INTO account (id, name, id_account_subtype) VALUES (16005, 'Muebles y Enseres', 16);
INSERT INTO account (id, name, id_account_subtype) VALUES (16006, 'Equipo de Cocina y Lavandería', 16);
INSERT INTO account (id, name, id_account_subtype) VALUES (16007, 'Otros Activos Fijos', 16);
INSERT INTO account (id, name, id_account_subtype) VALUES (16100, 'Edificio', 161);
INSERT INTO account (id, name, id_account_subtype) VALUES (16101, 'Equipo de Oficina', 161);
INSERT INTO account (id, name, id_account_subtype) VALUES (16102, 'Equipo de Médico y Enfermería', 161);
INSERT INTO account (id, name, id_account_subtype) VALUES (16103, 'Transporte', 161);
INSERT INTO account (id, name, id_account_subtype) VALUES (16104, 'Equipo de Aire Acondicionado', 161);
INSERT INTO account (id, name, id_account_subtype) VALUES (16105, 'Muebles y Enseres', 161);
INSERT INTO account (id, name, id_account_subtype) VALUES (16106, 'Equipo de Cocina y Lavandería', 161);
INSERT INTO account (id, name, id_account_subtype) VALUES (16107, 'Otros Activos Fijos', 161);
INSERT INTO account (id, name, id_account_subtype) VALUES (21000, 'Cta. Por Pagar - Nutre Hogar Rifa', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21001, 'Cta. Por Pagar - Nutre Hogar Nacional', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21002, 'Cta. Por Pagar - Distribuidora Pimentel', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21003, 'Cta. Por Pagar - Almacén Siempre Hay', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21004, 'Cta. Por Pagar - Farmacia Selecta', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21005, 'Cta. Por Pagar - Súper Farmacia Universal', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21006, 'Cta. Por Pagar - Supermercado La Huaca', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21007, 'Cta. Por Pagar - Supercentro Changuinola', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21008, 'Cta. Por Pagar - Cable & Wireless Panamá', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21009, 'Cta. Por Pagar - Grupo Anvered, S.A.', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21010, 'Cta. Por Pagar - Ventas A.C.M., S.A.', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21011, 'Cta. Por Pagar - Productos Toledano, S.A.', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21012, 'Cta. Por Pagar - Edechi, S.A.', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21013, 'Cta. Por Pagar - Frutas y Legumbres jara', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21014, 'Cta. Por Pagar - Distribuidora Fon', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21016, 'Cta. Por Pagar - Laboratorio Navarro, S.A.', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21017, 'Cta. Por Pagar - Préstamos', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21018, 'Cta. Por Pagar - Actividades', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (21019, 'Cta. Por Pagar - Otros', 21);
INSERT INTO account (id, name, id_account_subtype) VALUES (22000, 'Cta. Por Pagar - Seg. Social - Empleado', 22);
INSERT INTO account (id, name, id_account_subtype) VALUES (22001, 'Cta. Por Pagar - Seg. Educativo - Empleado', 22);
INSERT INTO account (id, name, id_account_subtype) VALUES (22002, 'Cta. Por Pagar - Descuento Bancario', 22);
INSERT INTO account (id, name, id_account_subtype) VALUES (22003, 'Cta. Por Pagar - Seg. Social - Patronal', 22);
INSERT INTO account (id, name, id_account_subtype) VALUES (22004, 'Cta. Por Pagar - Seg. Educativo - Patronal', 22);
INSERT INTO account (id, name, id_account_subtype) VALUES (22005, 'Cta. Por Pagar - Riego Profesional', 22);
INSERT INTO account (id, name, id_account_subtype) VALUES (39990, 'Patrimonio', 3999);
INSERT INTO account (id, name, id_account_subtype) VALUES (39998, 'Excedente Ganancia o Pérdida - Mensual', 3999);
INSERT INTO account (id, name, id_account_subtype) VALUES (39999, 'Excedente Ganancia o Pérdida - Anual', 3999);
INSERT INTO account (id, name, id_account_subtype) VALUES (41000, 'Ingresos - Actividad', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41002, 'Ingresos - Campaña Los Niños Primero', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41003, 'Ingresos - Donaciones Fijas', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41004, 'Ingresos - Donaciones', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41005, 'Ingresos - Subsidio del Municipio', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41006, 'Ingresos - Subsidio del MIDES', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41007, 'Ingresos - Subsidio de la Lotería', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41008, 'Ingresos - Dividendo de Nutre Hogar Rifa', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41009, 'Ingresos - NHN - Apoyo Cuota Patronal', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41010, 'Ingresos - Ventas', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41011, 'Ingresos - Alquiler', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (41012, 'Ingresos - Otros', 41);
INSERT INTO account (id, name, id_account_subtype) VALUES (42001, 'Ing. Donacion - Alimentos', 42);
INSERT INTO account (id, name, id_account_subtype) VALUES (42002, 'Ing. Donacion - Útiles Aseo y Limpieza', 42);
INSERT INTO account (id, name, id_account_subtype) VALUES (42003, 'Ing. Donacion - Enseres', 42);
INSERT INTO account (id, name, id_account_subtype) VALUES (42004, 'Ing. Donacion - Ropa de los Niños', 42);
INSERT INTO account (id, name, id_account_subtype) VALUES (42005, 'Ing. Donacion - Juguetes', 42);
INSERT INTO account (id, name, id_account_subtype) VALUES (42006, 'Ing. Donacion - Equipos', 42);
INSERT INTO account (id, name, id_account_subtype) VALUES (42007, 'Ing. Donacion - Otros', 42);
INSERT INTO account (id, name, id_account_subtype) VALUES (51000, 'Gastos - Actividades', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51001, 'Gastos - Planilla', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51002, 'Gastos - Vacaciones', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51003, 'Gastos - Décimo Tercer mes', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51004, 'Gastos - Prima de Antigüedad', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51005, 'Gastos - Indemnizacion', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51006, 'Gastos - Pre-Aviso', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51007, 'Gastos - Teléfono', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51008, 'Gastos - Luz', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51009, 'Gastos - Agua', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51010, 'Gastos - Recolección de la Basura', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51011, 'Gastos - Gas', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51012, 'Gastos - Alimentos', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51013, 'Gastos - Útiles de Limpieza y Aseo', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51014, 'Gastos - Enseres', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51015, 'Gastos - Medicamentos', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51016, 'Gastos - Útiles de Oficina y Papelería', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51017, 'Gastos - Chequera', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51018, 'Gastos - Transporte de la Oficina', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51019, 'Gastos - Transporte de la Enfermería', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51020, 'Gastos - Flete y Acarreo', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51021, 'Gastos - Junta Directiva', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51022, 'Gastos - Capacitación', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51023, 'Gastos - Comisión Bancaria', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51024, 'Gastos - Viáticos', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51025, 'Gastos - Hospedaje', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51026, 'Gastos - Laboratorio o Clínica', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51027, 'Gastos - Combustible', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51028, 'Gastos - Funerario', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51029, 'Gastos - Depreciación', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51030, 'Mant. Y Reparación de Edificio', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51031, 'Mant. Y Reparación de Equipo', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51032, 'Mant. Y Reparación de Equipo de Oficina', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51033, 'Mant. Y Reparación de E. Lavand. Y Cocina', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51034, 'Gastos - Útiles de Cocina', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51035, 'Gastos - Ropa de los Niños', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51036, 'Gastos - Ropa de Cama, Toallas y Otros', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51037, 'Gastos - Uniforme del Personal', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51038, 'Gastos - Escolar', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51039, 'Gastos - Misceláneos', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51040, 'Gastos - Servicios Profesionales', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51041, 'Gastos - Cuota Patronal', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (51042, 'Gastos - Otros', 51);
INSERT INTO account (id, name, id_account_subtype) VALUES (52000, 'Consumo de Alimentos', 52);
INSERT INTO account (id, name, id_account_subtype) VALUES (52001, 'Donación - Limpieza y Aseo', 52);
INSERT INTO account (id, name, id_account_subtype) VALUES (52002, 'Donación - Enseres', 52);
INSERT INTO account (id, name, id_account_subtype) VALUES (52003, 'Donación - Medicamentos', 52);
INSERT INTO account (id, name, id_account_subtype) VALUES (52004, 'Donación - Bolsa de Alimentos', 52);
INSERT INTO account (id, name, id_account_subtype) VALUES (52005, 'Productos Vencidos o Dañados', 52);
INSERT INTO account (id, name, id_account_subtype) VALUES (52006, 'Donación - Otros', 52);
