-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '1', 'ACTIVO', 'ACTIVO', 'Cuentas Activas');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '11', 'ACTIVO Corriente', 'ACTIVO', 'Cuentas Activas Corrientes');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '11020', 'Caja Menuda', 'ACTIVO', 'Caja Menuda para gastos menores');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '11030', 'Caja Menuda del MIDES', 'ACTIVO', 'Caja Menuda para el MIDES');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '11051', 'Banco Global Bank Corp', 'ACTIVO', 'Cuenta del Banco Global Bank Corp');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '11090', 'Caja General', 'ACTIVO', 'Caja General para operaciones');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '11100', 'Gastos Pagados Por Adelantado', 'ACTIVO', 'Gastos que se han pagado antes de recibir el servicio');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '13', 'Inventario', 'ACTIVO', 'Inventario de bienes');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '13000', 'Alimentos', 'ACTIVO', 'Inventario de alimentos');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '13001', 'Útiles de Limpieza y Aseo', 'ACTIVO', 'Inventario de útiles de limpieza');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '13002', 'Enseres', 'ACTIVO', 'Inventario de enseres');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '13003', 'Medicamentos', 'ACTIVO', 'Inventario de medicamentos');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '13004', 'Ropa de Los Niños', 'ACTIVO', 'Inventario de ropa para niños');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '13005', 'Juguetes', 'ACTIVO', 'Inventario de juguetes');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '13006', 'Otros', 'ACTIVO', 'Otros artículos en inventario');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '15', 'Cuentas Por Cobrar', 'ACTIVO', 'Cuentas por cobrar a terceros');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '15000', 'Cta. Por Cobrar - Empleados', 'ACTIVO', 'Cuentas por cobrar a empleados');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '15001', 'Cta. Por Cobrar - Actividad', 'ACTIVO', 'Cuentas por cobrar por actividades');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '15002', 'Cta. Por Cobrar - Cuotas', 'ACTIVO', 'Cuentas por cobrar por cuotas');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '15003', 'Cta. Por Cobrar - Nutre Hogar Nacional', 'ACTIVO', 'Cuentas por cobrar de Nutre Hogar Nacional');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '15004', 'Cta. Por Cobrar - Nutre Hogar Rifa', 'ACTIVO', 'Cuentas por cobrar de Nutre Hogar Rifa');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '15005', 'Cta. Por Cobrar - Mides', 'ACTIVO', 'Cuentas por cobrar de Mides');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '15006', 'Cta. Por Cobrar - Otros', 'ACTIVO', 'Cuentas por cobrar a otros');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16', 'ACTIVOs Fijos', 'ACTIVO', 'Cuentas de ACTIVOs fijos');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16000', 'Edificio', 'ACTIVO', 'Cuentas de edificios');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16001', 'Equipo de Oficina', 'ACTIVO', 'Cuentas de equipo de oficina');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16002', 'Equipo de Medico y Enfermería', 'ACTIVO', 'Cuentas de equipo médico');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16003', 'Transporte', 'ACTIVO', 'Cuentas de transporte');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16004', 'Equipo de Aire Acondicionado', 'ACTIVO', 'Cuentas de aire acondicionado');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16005', 'Muebles y Enseres', 'ACTIVO', 'Cuentas de muebles y enseres');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16006', 'Equipo de Cocina y Lavandería', 'ACTIVO', 'Cuentas de equipo de cocina');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16007', 'Otros ACTIVOs Fijos', 'ACTIVO', 'Otros ACTIVOs fijos');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '161', 'Depreciación Acumulada', 'PASIVO', 'Cuentas de depreciación acumulada');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16100', 'Edificio', 'PASIVO', 'Depreciación acumulada del edificio');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16101', 'Equipo de Oficina', 'PASIVO', 'Depreciación acumulada del equipo de oficina');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16102', 'Equipo de Médico y Enfermería', 'PASIVO', 'Depreciación acumulada del equipo médico');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16103', 'Transporte', 'PASIVO', 'Depreciación acumulada del transporte');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16104', 'Equipo de Aire Acondicionado', 'PASIVO', 'Depreciación acumulada de aire acondicionado');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16105', 'Muebles y enseres', 'PASIVO', 'Depreciación acumulada de muebles');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16106', 'Equipo de Cocina y Lavandería', 'PASIVO', 'Depreciación acumulada de equipo de cocina');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '16107', 'Otros ACTIVOs Fijos', 'PASIVO', 'Depreciación acumulada de otros ACTIVOs fijos');

-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '2', 'PASIVOs', 'PASIVO', 'Cuentas de PASIVOs');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21', 'Cuentas Por Pagar', 'PASIVO', 'Cuentas por pagar a terceros');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21000', 'Cta. Por Pagar - Nutre Hogar Rifa', 'PASIVO', 'Cuentas por pagar de Nutre Hogar Rifa');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21001', 'Cta. Por Pagar - Nutre Hogar Nacional', 'PASIVO', 'Cuentas por pagar de Nutre Hogar Nacional');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21002', 'Cta. Por Pagar - Distribuidora Pimentel', 'PASIVO', 'Cuentas por pagar a Distribuidora Pimentel');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21003', 'Cta. Por Pagar - Almacén Siempre Hay', 'PASIVO', 'Cuentas por pagar a Almacén Siempre Hay');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21004', 'Cta. Por Pagar - Farmacia Selecta', 'PASIVO', 'Cuentas por pagar a Farmacia Selecta');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21005', 'Cta. Por Pagar - Súper Farmacia Universal', 'PASIVO', 'Cuentas por pagar a Súper Farmacia Universal');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21006', 'Cta. Por Pagar - Supermercado La Huaca', 'PASIVO', 'Cuentas por pagar a Supermercado La Huaca');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21007', 'Cta. Por Pagar - Supercentro Changuinola', 'PASIVO', 'Cuentas por pagar a Supercentro Changuinola');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21008', 'Cta. Por Pagar - Cable & Wireless Panamá', 'PASIVO', 'Cuentas por pagar a Cable & Wireless Panamá');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21009', 'Cta. Por Pagar - Grupo Anvered, S.A.', 'PASIVO', 'Cuentas por pagar a Grupo Anvered, S.A.');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21010', 'Cta. Por Pagar - Ventas A.C.M., S.A.', 'PASIVO', 'Cuentas por pagar a Ventas A.C.M., S.A.');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21011', 'Cta. Por Pagar - Productos Toledanos, S.A.', 'PASIVO', 'Cuentas por pagar a Productos Toledanos, S.A.');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21012', 'Cta. Por Pagar - Edechi, S.A.', 'PASIVO', 'Cuentas por pagar a Edechi, S.A.');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21013', 'Cta. Por Pagar - Frutas y Legumbres Jara', 'PASIVO', 'Cuentas por pagar a Frutas y Legumbres Jara');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21014', 'Cta. Por Pagar - Distribuidora Fon', 'PASIVO', 'Cuentas por pagar a Distribuidora Fon');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '21015', 'Cta. Por Pagar - Nutre Hogar Nacional', 'PASIVO', 'Cuentas por pagar a Nutre Hogar Nacional');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '3', 'PATRIMONIO', 'PATRIMONIO', 'Cuentas de PATRIMONIO');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '31', 'Capital', 'PATRIMONIO', 'Capital de la organización');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '311', 'Donaciones', 'PATRIMONIO', 'Donaciones recibidas por la organización');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '31100', 'Donaciones Efectuadas', 'PATRIMONIO', 'Donaciones efectuadas');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '31101', 'Donaciones a Nutre Hogar Nacional', 'PATRIMONIO', 'Donaciones a Nutre Hogar Nacional');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '31102', 'Donaciones a Nutre Hogar Rifa', 'PATRIMONIO', 'Donaciones a Nutre Hogar Rifa');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '31103', 'Donaciones a la Fundacion Dr. José Antonio Sosa', 'PATRIMONIO', 'Donaciones a la Fundación Dr. José Antonio Sosa');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '31104', 'Donaciones a Fundacion Luz y Esperanza', 'PATRIMONIO', 'Donaciones a Fundación Luz y Esperanza');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '31105', 'Donaciones a la Fundación Niños de Panamá', 'PATRIMONIO', 'Donaciones a la Fundación Niños de Panamá');
INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '31106', 'Donaciones a otras fundaciones', 'PATRIMONIO', 'Donaciones a otras fundaciones');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '312', 'Aportaciones', 'PATRIMONIO', 'Aportaciones de los miembros');
-- INSERT INTO Cuentas (id_cuenta, codigo_cuenta, descripcion, tipo_cuenta, nombre_cuenta) VALUES (null, '4', 'RESULTADOS', 'RESULTADOS', 'RESULTADOS de la organización');
