/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nutrehogar.sistemacontable.ui.view.crud;

import com.nutrehogar.sistemacontable.domain.DocumentType;
import com.nutrehogar.sistemacontable.domain.model.Account;
import com.nutrehogar.sistemacontable.application.view.crud.AccountingEntryFormView;
import lombok.Getter;

import javax.swing.*;

/**
 * @author Calci
 */
@Getter
public class DefaultAccountEntryFormView extends AccountingEntryFormView {

    /**
     * Creates new form DefaultAccountEntryFormView
     */
    public DefaultAccountEntryFormView() {
        initComponents();
        txtEntryName.putClientProperty("JTextField.placeholderText", "Ventas S.A.");
        taEntryConcept.putClientProperty("JTextArea.placeholderText", "Cancelación de factura al crédito");
        txtEntryDocumentNumber.putClientProperty("JTextField.placeholderText", "120");
        txtEntryCheckNumber.putClientProperty("JTextField.placeholderText", "4987");
        txtRecordReference.putClientProperty("JTextField.placeholderText", "Pago de factura");
        txtRecordAmount.putClientProperty("JTextField.placeholderText", "12.50");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgRecordType = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        pnlAside = new javax.swing.JPanel();
        pnlLedgerRecordOperations = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        lblAdd = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        lblDelete = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        pnlRecordForm = new javax.swing.JPanel();
        lblRecordAmount = new javax.swing.JLabel();
        txtRecordAmount = new javax.swing.JTextField();
        lblRecordAccount = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        cbxRecordAccount = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        lblSave = new javax.swing.JLabel();
        lblUpdate = new javax.swing.JLabel();
        txtRecordReference = new javax.swing.JTextField();
        lblRecordReference = new javax.swing.JLabel();
        lblRecordType = new javax.swing.JLabel();
        rbtRecordDebit = new javax.swing.JRadioButton();
        rbtRecordCredit = new javax.swing.JRadioButton();
        auditablePanel = new com.nutrehogar.sistemacontable.ui.JComponents.AuditablePanel();
        pnlEntryForm = new javax.swing.JPanel();
        lblEntryName = new javax.swing.JLabel();
        txtEntryName = new javax.swing.JTextField();
        lblConcept = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taEntryConcept = new javax.swing.JTextArea();
        lblEntryDocumentNumber = new javax.swing.JLabel();
        txtEntryDocumentNumber = new javax.swing.JTextField();
        lblEntryDate = new javax.swing.JLabel();
        txtEntryCheckNumber = new javax.swing.JTextField();
        lblEntryCeckNumber = new javax.swing.JLabel();
        spnEntryDate = new com.nutrehogar.sistemacontable.ui.components.LocalDateSpinner();
        btnSaveEntry = new javax.swing.JButton();
        btnUpdateEntry = new javax.swing.JButton();
        btnDeleteEntry = new javax.swing.JButton();
        btnAddEntry = new javax.swing.JButton();
        cbxEntryDocumentType = new javax.swing.JComboBox<>();
        pnlSourceDocuments = new javax.swing.JPanel();
        btnGeneratePaymentVoucher = new javax.swing.JButton();
        btnGenerateRegistrationForm = new javax.swing.JButton();
        lblCreateBy = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCreateAt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUpdateBy = new javax.swing.JLabel();
        lblUpdateAt = new javax.swing.JLabel();

        setOpaque(false);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "a", null, "a"},
                {null, null, "aa", null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        pnlAside.setOpaque(false);

        pnlLedgerRecordOperations.setBorder(javax.swing.BorderFactory.createTitledBorder(" Operaciones "));
        pnlLedgerRecordOperations.setOpaque(false);

        btnAdd.setText("Crear");

        lblAdd.setLabelFor(btnAdd);
        lblAdd.setText("<html><p>Agregar un nuevo registro </p></html>");
        lblAdd.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblAdd.setPreferredSize(new java.awt.Dimension(250, 40));

        lblEdit.setLabelFor(btnEdit);
        lblEdit.setText("<html><p>Editar el registro seleccionado</p></html>");
        lblEdit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblEdit.setPreferredSize(new java.awt.Dimension(250, 40));

        btnEdit.setText("Editar");

        lblDelete.setLabelFor(btnDelete);
        lblDelete.setText("<html><p>Elimina el registro seleccionado</p></html>");
        lblDelete.setToolTipText("");
        lblDelete.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblDelete.setPreferredSize(new java.awt.Dimension(250, 40));

        btnDelete.setText("Eliminar");

        javax.swing.GroupLayout pnlLedgerRecordOperationsLayout = new javax.swing.GroupLayout(pnlLedgerRecordOperations);
        pnlLedgerRecordOperations.setLayout(pnlLedgerRecordOperationsLayout);
        pnlLedgerRecordOperationsLayout.setHorizontalGroup(
            pnlLedgerRecordOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLedgerRecordOperationsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLedgerRecordOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLedgerRecordOperationsLayout.createSequentialGroup()
                        .addComponent(lblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlLedgerRecordOperationsLayout.createSequentialGroup()
                        .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlLedgerRecordOperationsLayout.createSequentialGroup()
                        .addComponent(lblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLedgerRecordOperationsLayout.setVerticalGroup(
            pnlLedgerRecordOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLedgerRecordOperationsLayout.createSequentialGroup()
                .addGroup(pnlLedgerRecordOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLedgerRecordOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLedgerRecordOperationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete)))
        );

        pnlRecordForm.setBorder(javax.swing.BorderFactory.createTitledBorder(" Registro Contable "));
        pnlRecordForm.setOpaque(false);

        lblRecordAmount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRecordAmount.setLabelFor(txtRecordAmount);
        lblRecordAmount.setText("Monto:");
        lblRecordAmount.setName(""); // NOI18N

        lblRecordAccount.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRecordAccount.setLabelFor(cbxRecordAccount);
        lblRecordAccount.setText("Cuenta:");

        btnSave.setText("Guardar");

        cbxRecordAccount.setModel(new javax.swing.DefaultComboBoxModel<>());

        btnUpdate.setText("Actualizar");

        lblSave.setLabelFor(btnSave);
        lblSave.setText("<html><p>Agrega el nuevo registro a la entrada contable</p></html>");
        lblSave.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSave.setPreferredSize(new java.awt.Dimension(250, 40));

        lblUpdate.setLabelFor(btnUpdate);
        lblUpdate.setText("<html><p>Actualiza los datos de la entrada editada</p></html>");
        lblUpdate.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblUpdate.setPreferredSize(new java.awt.Dimension(250, 40));

        lblRecordReference.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRecordReference.setLabelFor(txtRecordReference);
        lblRecordReference.setText("Referencia:");

        lblRecordType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRecordType.setLabelFor(rbtRecordDebit);
        lblRecordType.setText("Tipo de Registro:");

        bgRecordType.add(rbtRecordDebit);
        rbtRecordDebit.setText("Débito");

        bgRecordType.add(rbtRecordCredit);
        rbtRecordCredit.setText("Crédito");

        javax.swing.GroupLayout pnlRecordFormLayout = new javax.swing.GroupLayout(pnlRecordForm);
        pnlRecordForm.setLayout(pnlRecordFormLayout);
        pnlRecordFormLayout.setHorizontalGroup(
            pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecordFormLayout.createSequentialGroup()
                        .addGroup(pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRecordAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRecordReference, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRecordType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtRecordDebit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtRecordCredit, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecordFormLayout.createSequentialGroup()
                        .addComponent(lblRecordAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRecordReference, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxRecordAccount, javax.swing.GroupLayout.Alignment.TRAILING, 0, 253, Short.MAX_VALUE)
                            .addComponent(txtRecordAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRecordFormLayout.createSequentialGroup()
                        .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecordFormLayout.createSequentialGroup()
                        .addComponent(lblSave, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlRecordFormLayout.setVerticalGroup(
            pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecordFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRecordReference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRecordReference))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecordAccount)
                    .addComponent(cbxRecordAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecordType)
                    .addComponent(rbtRecordDebit)
                    .addComponent(rbtRecordCredit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecordAmount)
                    .addComponent(txtRecordAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(lblSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecordFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAsideLayout = new javax.swing.GroupLayout(pnlAside);
        pnlAside.setLayout(pnlAsideLayout);
        pnlAsideLayout.setHorizontalGroup(
            pnlAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRecordForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLedgerRecordOperations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(auditablePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAsideLayout.setVerticalGroup(
            pnlAsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAsideLayout.createSequentialGroup()
                .addComponent(pnlLedgerRecordOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRecordForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(auditablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pnlEntryForm.setBorder(javax.swing.BorderFactory.createTitledBorder("  Entrada de Diario  "));
        pnlEntryForm.setOpaque(false);

        lblEntryName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEntryName.setLabelFor(txtEntryName);
        lblEntryName.setText("Nombre:");

        txtEntryName.setMaximumSize(new java.awt.Dimension(500, 500));

        lblConcept.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblConcept.setLabelFor(taEntryConcept);
        lblConcept.setText("Concepto:");

        taEntryConcept.setColumns(20);
        taEntryConcept.setRows(5);
        taEntryConcept.setMaximumSize(new java.awt.Dimension(400, 400));
        jScrollPane2.setViewportView(taEntryConcept);

        lblEntryDocumentNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEntryDocumentNumber.setLabelFor(txtEntryDocumentNumber);
        lblEntryDocumentNumber.setText("Documento No:");

        lblEntryDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEntryDate.setLabelFor(spnEntryDate);
        lblEntryDate.setText("Fecha:");

        lblEntryCeckNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEntryCeckNumber.setLabelFor(txtEntryCheckNumber);
        lblEntryCeckNumber.setText("Cheque No:");

        btnSaveEntry.setText("Guadar");
        btnSaveEntry.setMaximumSize(new java.awt.Dimension(73, 23));
        btnSaveEntry.setMinimumSize(new java.awt.Dimension(73, 23));
        btnSaveEntry.setPreferredSize(new java.awt.Dimension(73, 23));

        btnUpdateEntry.setText("Actualizar");
        btnUpdateEntry.setMaximumSize(new java.awt.Dimension(73, 23));
        btnUpdateEntry.setMinimumSize(new java.awt.Dimension(73, 23));
        btnUpdateEntry.setPreferredSize(new java.awt.Dimension(73, 23));

        btnDeleteEntry.setText("Eliminar");

        btnAddEntry.setText("Nuevo");

        cbxEntryDocumentType.setModel(new javax.swing.DefaultComboBoxModel<>());
        cbxEntryDocumentType.setToolTipText("Tipo de Documento");
        cbxEntryDocumentType.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlEntryFormLayout = new javax.swing.GroupLayout(pnlEntryForm);
        pnlEntryForm.setLayout(pnlEntryFormLayout);
        pnlEntryFormLayout.setHorizontalGroup(
            pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntryFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblConcept, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(lblEntryName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtEntryName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEntryCeckNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEntryDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEntryDocumentNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEntryDocumentNumber)
                    .addComponent(spnEntryDate, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(txtEntryCheckNumber))
                .addGap(18, 18, 18)
                .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnUpdateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEntryFormLayout.createSequentialGroup()
                        .addComponent(cbxEntryDocumentType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEntryFormLayout.createSequentialGroup()
                        .addComponent(btnAddEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlEntryFormLayout.setVerticalGroup(
            pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEntryFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEntryFormLayout.createSequentialGroup()
                        .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEntryName)
                            .addComponent(txtEntryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEntryFormLayout.createSequentialGroup()
                                .addComponent(lblConcept)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(pnlEntryFormLayout.createSequentialGroup()
                        .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEntryDocumentNumber)
                            .addComponent(txtEntryDocumentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteEntry)
                            .addComponent(cbxEntryDocumentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEntryDate)
                            .addComponent(spnEntryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlEntryFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEntryCeckNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEntryCheckNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddEntry))))
                .addContainerGap())
        );

        cbxEntryDocumentType.getAccessibleContext().setAccessibleName("Tipo de Documento");

        pnlSourceDocuments.setBorder(javax.swing.BorderFactory.createTitledBorder("Documentos Fuente"));
        pnlSourceDocuments.setOpaque(false);

        btnGeneratePaymentVoucher.setText("Comprobante");

        btnGenerateRegistrationForm.setText("Formulario");
        btnGenerateRegistrationForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateRegistrationFormActionPerformed(evt);
            }
        });

        lblCreateBy.setText("nadie");

        jLabel1.setText("Creado por: ");

        jLabel2.setText("Fecha creación: ");

        lblCreateAt.setText("nada");

        jLabel4.setText("Actualizado por: ");

        jLabel3.setText("Fecha actualización: ");

        lblUpdateBy.setText("nadie");

        lblUpdateAt.setText("nada");

        javax.swing.GroupLayout pnlSourceDocumentsLayout = new javax.swing.GroupLayout(pnlSourceDocuments);
        pnlSourceDocuments.setLayout(pnlSourceDocumentsLayout);
        pnlSourceDocumentsLayout.setHorizontalGroup(
            pnlSourceDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSourceDocumentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSourceDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGeneratePaymentVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerateRegistrationForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlSourceDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSourceDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCreateBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCreateAt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSourceDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSourceDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUpdateAt)
                    .addComponent(lblUpdateBy))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        pnlSourceDocumentsLayout.setVerticalGroup(
            pnlSourceDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSourceDocumentsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSourceDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeneratePaymentVoucher)
                    .addComponent(jLabel1)
                    .addComponent(lblCreateBy)
                    .addComponent(jLabel4)
                    .addComponent(lblUpdateBy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSourceDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateRegistrationForm)
                    .addComponent(jLabel2)
                    .addComponent(lblCreateAt)
                    .addComponent(jLabel3)
                    .addComponent(lblUpdateAt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlEntryForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlSourceDocuments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlEntryForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlSourceDocuments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addComponent(pnlAside, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateRegistrationFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateRegistrationFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateRegistrationFormActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.nutrehogar.sistemacontable.ui.JComponents.AuditablePanel auditablePanel;
    private javax.swing.ButtonGroup bgRecordType;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddEntry;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteEntry;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGeneratePaymentVoucher;
    private javax.swing.JButton btnGenerateRegistrationForm;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveEntry;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateEntry;
    private javax.swing.JComboBox<DocumentType> cbxEntryDocumentType;
    private javax.swing.JComboBox<Account> cbxRecordAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblConcept;
    private javax.swing.JLabel lblCreateAt;
    private javax.swing.JLabel lblCreateBy;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblEntryCeckNumber;
    private javax.swing.JLabel lblEntryDate;
    private javax.swing.JLabel lblEntryDocumentNumber;
    private javax.swing.JLabel lblEntryName;
    private javax.swing.JLabel lblRecordAccount;
    private javax.swing.JLabel lblRecordAmount;
    private javax.swing.JLabel lblRecordReference;
    private javax.swing.JLabel lblRecordType;
    private javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblUpdate;
    private javax.swing.JLabel lblUpdateAt;
    private javax.swing.JLabel lblUpdateBy;
    private javax.swing.JPanel pnlAside;
    private javax.swing.JPanel pnlEntryForm;
    private javax.swing.JPanel pnlLedgerRecordOperations;
    private javax.swing.JPanel pnlRecordForm;
    private javax.swing.JPanel pnlSourceDocuments;
    private javax.swing.JRadioButton rbtRecordCredit;
    private javax.swing.JRadioButton rbtRecordDebit;
    private com.nutrehogar.sistemacontable.ui.components.LocalDateSpinner spnEntryDate;
    private javax.swing.JTextArea taEntryConcept;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtEntryCheckNumber;
    private javax.swing.JTextField txtEntryDocumentNumber;
    private javax.swing.JTextField txtEntryName;
    private javax.swing.JTextField txtRecordAmount;
    private javax.swing.JTextField txtRecordReference;

    @Override
    public JButton getBtnGenerateReport() {
        return null;
    }
    // End of variables declaration//GEN-END:variables
}
