jpackage `
--input .\Jar\ `
--name SistemaContable `
--main-jar SistemaContable-1.5-SNAPSHOT.jar `
--main-class com.nutrehogar.sistemacontable.application.Principal `
--type exe `
--icon .\Icon\icon.ico `
--vendor "Universidad Tecnológica de Panamá - LIC. EN DESARROLLO DE SOFTWARE (2016-M)" `
--description "Sistema de Contabilidad para Nutre Hogar" `
--app-version 1.5 `
--verbose `
--win-shortcut `
--win-menu `
--win-dir-chooser